# fly.toml app configuration file generated for fithub-autumn-dew-5749 on 2025-09-25T21:34:48-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fithub-autumn-dew-5749'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = "production"